//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinWebDiff.rc

#define IDR_MAINFRAME			128
#define IDD_WINWEBDIFF_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDM_FILE_NEW            106
#define IDM_FILE_NEW3           107
#define IDM_FILE_NEW_TAB        108
#define IDM_FILE_CLOSE_TAB      109
#define IDM_FILE_RELOAD         110
#define IDM_FILE_GENERATE_REPORT 111
#define IDM_VIEW_SIZE_FIT_TO_WINDOW 120
#define IDM_VIEW_SIZE_320x512   121
#define IDM_VIEW_SIZE_375x600   122
#define IDM_VIEW_SIZE_1024x640  123
#define IDM_VIEW_SIZE_1280x800  124
#define IDM_VIEW_SIZE_1440x900  125
#define IDM_VIEW_SPLITHORIZONTALLY 126
#define IDM_VIEW_VIEWDIFFERENCES 127
#define IDM_VIEW_DIFF_ALGORITHM_MYERS 128
#define IDM_VIEW_DIFF_ALGORITHM_MINIMAL 129
#define IDM_VIEW_DIFF_ALGORITHM_PATIENCE 130
#define IDM_VIEW_DIFF_ALGORITHM_HISTOGRAM 131
#define IDM_VIEW_DIFF_ALGORITHM_NONE 132
#define IDM_COMPARE_RECOMPARE 140
#define IDM_COMPARE_SCREENSHOTS 141
#define IDM_COMPARE_FULLSIZE_SCREENSHOTS 142
#define IDM_COMPARE_HTML        143
#define IDM_COMPARE_TEXT        144
#define IDM_COMPARE_RESOURCE_TREE         145
#define IDM_COMPARE_NEXTDIFFERENCE 146
#define IDM_COMPARE_PREVIOUSDIFFERENCE 147
#define IDM_COMPARE_FIRSTDIFFERENCE 148
#define IDM_COMPARE_LASTDIFFERENCE 149
#define IDM_COMPARE_NEXTCONFLICT 150
#define IDM_COMPARE_PREVIOUSCONFLICT 151
#define IDM_SYNC_ENABLED        160
#define IDM_SYNC_SCROLL         161
#define IDM_SYNC_CLICK          162
#define IDM_SYNC_INPUT          163
#define IDM_CLEAR_DISK_CACHE    171
#define IDM_CLEAR_COOKIES       172
#define IDM_CLEAR_BROWSING_HISTORY 173
#define IDM_CLEAR_ALL_PROFILE   174
#define IDI_WINWEBDIFF			180
#define IDI_SMALL				181
#define IDC_WINWEBDIFF			182
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	190
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		111
#endif
#endif
